### ISSUE TITLE
Analyze request fields without @Tripwired

### ISSUE THREAD

**Issue by mstaudt** [ctrl-alt-dev/harbinger#1]
Hello,

I recently stumbled upon your project and really like it.  There is a feature I'd like to suggest you.

By now, the `@Tripwired` annotation has to be used on forms and DTOs to detect potentially malicious input. Our application contains a whole bunch of forms making this solution quite uncomfortable.
If the `HttpEvidenceFilter` is extended to automatically iterate through all the `HttpServletRequest`'s parameters that come in, this functionality does not need the `@Tripwired` annotation.

I tested it by extending the filter and it works fine. 
`HttpEvidenceFilter.java`:
```
public class HttpEvidenceFilter extends OncePerRequestFilter {

    ...

    @Override
    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain chain) throws ServletException, IOException {
        Evidence evidence = new Evidence(request);
        analyzeRequest(request);

        ...
    }

    protected void analyzeRequest(HttpServletRequest request) {
        Map<String, String[]> parameterMap = request.getParameterMap();
        parameterMap.values().stream().forEach(values -> analyze(values));
    }

    protected void analyze(String[] values) {
         Arrays.stream(values).forEach(value -> this.ctx.isValid(value));
    }
}
```

**Comment by ctrl-alt-dev** [comment]
Thank you for your interest in Harbinger!

I understand why you would want to validate all form fields against potential malicious input. 

However you may want to consider the following:
- False Positives - sometimes correct input may look malicious and trigger a detection rule. In that case you would want to exclude that field from that specific rule (or all rules).
- REST based applications typically use JSON bodies and therefore cannot be validated using HTTP parameters.  Typically they are validated by mapping them to DTO's and use bean validation.

This is why I ended up making a fine grained solution.  Pick a few obvious fields (username, password etc) `@Tripwire` them and see what happens :-)

So, while your catch-all approach certainly works, I wonder what would be a good way exclude certain parameters on some forms from validation?

**Comment by ctrl-alt-dev** [comment]
I've added a WhiteListing feature and the (all) HTTP parameters checking. The response decider can now act on those parameters too.
